### ISSUE TITLE
Add an open source license

### ISSUE THREAD

**Issue by byco** [openoakland/openbudgetoakland#134]
Hi all!

I'm from Oakland so I was intrigued when I stumbled upon this project. I noticed on your website that this is described as an open source project, but I don't see a license for the Github repo, so I'm hesitating about contributing code since there may be a liability issue.

It's a best practice to add an open source license for community projects. According to Github: "without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license."

https://help.github.com/en/articles/licensing-a-repository

Anyway, I suggest using an MIT license since that's a good, simple one. Some comparisons on different licenses here: https://choosealicense.com/

**Comment by nydame** [comment]
byco makes an excellent point! Reviewing different licenses for open source software, then adding one in a pull request would be a great and super-easy first project. If no one takes this on in the next couple of weeks, I'll just do it myself.

**Comment by skullsai** [comment]
Hey @byco  and @nydame, I came across this issue from the @first_isuues twitter bot. Although I am not from Oakland I am extremely interested in how open source licenses work and how to chose and obtain it for new repositories. I would like to help obtain an open source license for this repository. Could I please be assigned to this issue?

**Comment by nydame** [comment]
@skullsai, it's all yours. Our project is undergoing a leadership change, and I just noticed that I don't have the power to add team members yet. If you want to get going now, just fork our repo, add your changes (along with a comment explaining your choice of license), and push the changes upstream. 

I hope that made sense. I will invite you to the team and assign you to this issue as soon as I am able.

**Comment by skullsai** [comment]
Hey @nydame  and @byco, I added an MIT license with what I think were the right reasons.

Please take a look at it my PR  #136 where have given an elaborate understanding of the same and let me know what you think.
