### ISSUE TITLE
Remove placeholder video embed from Budget Timeline slide 2

### ISSUE THREAD

**Issue by theecrit** [openoakland/openbudgetoakland#172]
## Description
The current timeline.js embed displays a default timeline.js video ad instead of budget-related content.

## Proposed solution
Remove the video from the Google Sheet (or json; not sure which the site uses) feeding the timeline content. Or replace it with more relevant media.

**Comment by nydame** [comment]
Thanks, Jess. We are starting to take on the updating of the timeline in earnest. I just removed the offending video. Cheers!
