### ISSUE TITLE
Found broken links on openbudgetoakland

### ISSUE THREAD

**Issue by aenygma** [openoakland/openbudgetoakland#190]
An link checking audit scan from https://www.deadlinkchecker.com/ came up with the following results.

Status | URL | Source link text | Page 
-- | -- | -- | -- 
-1 Not found: The date in the certificate is invalid or has expired | https://www.lanelookout.org/ | Visit site | https://openoakland.org/projects/
403 Forbidden | http://www.insidebayarea.com/news/ci_21464979/openoakland-brigade-tries-unite-techies-community-advocates-and | OpenOakland Brigade tries to unite techies, community advocates and city hall | https://openoakland.org/press/
502 Bad Gateway | https://techpresident.com/news/23749/oakland-gets-new-data-visualization-site-its-budget | Oakland Gets a New Data Visualization Site for its Budget [301 from http://techpresident.com/news/23749/oakland-gets-new-data-visualization-site-its-budget] | https://openoakland.org/press/
404 Not Found | https://eastbayexpress.com/ebx/cracking-oaklands-code/Content?oid=3426694 | Cracking Oaklandâs Code -Â Can a group of hackers figure out new answers to the cityâs old problems? [301 from http://www.eastbayexpress.com/ebx/cracking-oaklands-code/Content?oid=3426694] [301 from https://www.eastbayexpress.com/ebx/cracking-oaklands-code/Content?oid=3426694] | https://openoakland.org/press/
-1 Timeout | http://www.whatcountsforamerica.org/portfolio/three-data-access-trends-shaping-the-future-of-community-development-open-data-my-data-and-smart-disclosure/ | Three Data Access Trends Shaping the Future of Community Development: Open Data, My Data, and Smart Disclosure | https://openoakland.org/press/

**Comment by nydame** [comment]
Thanks for finding these. However, all of the bad links are on the parent org's website, not on Open Budget: Oakland's. I will bring them to the attention of the right people.
