### ISSUE TITLE
Link to budget analysis document by Rose Associates

### ISSUE THREAD

**Issue by nydame** [openoakland/openbudgetoakland#233]
Add the report by Harvey M. Rose Associates LLC on their budget and finance analysis of Oakland's Proposed Fiscal Year 2021 - 2023 Budget. It can be found here: https://oakland.legistar.com/LegislationDetail.aspx?ID=4937156&GUID=43F7BF0F-E398-425F-B634-DB8D9DD7FFE7&Options=&Search=. Link to it on Legistar and provide a link to download both PDFs.

This content probably belongs on the News page.

**Comment by tinyherocarrot** [comment]
Hi I'd like to take this issue!

**Comment by nydame** [comment]
Completed.
