### ISSUE TITLE
Optimize for mobile

### ISSUE THREAD

**Issue by evanwolf** [openoakland/openbudgetoakland#43]
to start: 
- minimize bits downloaded
- redesign for touch UI (cards? http://blog.intercom.io/why-cards-are-the-future-of-the-web/)
- redesign for smaller screens (e.g. do our datavizs still work?)
- mobile social and sharing
- any location-based data (e.g. geocoded capital budgets, like a given library building or a road)

**Comment by macfarlandian** [comment]
ongoing effort too complex to capture in a single issue; closing.
