### ISSUE TITLE
Add a blog to the site

### ISSUE THREAD

**Issue by evanwolf** [openoakland/openbudgetoakland#44]
The project has lots of public communication to do. Including: 
- New-data announcements (as we refresh)
- OBO Launch activities
- New feature introductions and explanations
- Request for testers and other volunteers
- Announcing City Council activity re: the budget
- Pointing to public reporting and analysis of OBO and the budget
- Kudos and thanks to other brigades for their projects; to Oakland staff for opening up the data
- Project media kit for reporters (pictures of the app, the team; quotable text; links to resources)

**Comment by macfarlandian** [comment]
no plans to add this functionality to the site at this point; closing.
