### ISSUE TITLE
What is happening with the current budget cycle?

### ISSUE THREAD

**Issue by mikeubell** [openoakland/openbudgetoakland#50]
I am curious if you have plans to visualize any of the proposed budgets  or the 5 year forecast?

**Comment by evanwolf** [comment]
I'd love to see how our budgets compare to other cities on $/resident. Do we spend more or less than San Jose and Bakersfield on IT? on fire? on police? on roads? Do we get our fair share of state/federal infrastructure funds?

**Comment by adstiles** [comment]
We are going to do updated treemap and sankey (flow) diagram for proposed budget. Data isn't available until at least May 1 when budget is announced. Considering something for 5-year forecast.

**Comment by adstiles** [comment]
@evanwolf I agree that'd be a good comparison. Do those cities release budget data?

**Comment by adstiles** [comment]
Here's the relevant pages from the 5-year report:

![5-year forecast summary copy](https://cloud.githubusercontent.com/assets/2553203/6657787/37ade250-cb13-11e4-888f-695df522e3fd.jpg)

**Comment by adstiles** [comment]
[Bullet points continued]

 Issued a pension bond to reduce/refinance PFRS outstanding debt and increase funding ratio to the amount of $250 million in 2012;
 Negotiated with Oakland Police Officer’s Association to make 9% contribution toward their pension effective July 2011, Local 55, International Association of Firefighters members contribute 13%, Civilian employees contribute 8%; and,
 Adopted and implemented the third tier of the pension benefit level, which further modified for public safety employees from 3% @50 formula to 2.7% @ 57 and for civilian employees from 2.5% @55 to 2.00% @ 62 effective January 2013.

The issues the City is facing relative to unfunded liabilities, increased fringe benefits, and deferred maintenance are not unique to Oakland. Cities, states, and countries around the world are dealing with these same issues. As such, staff will continue to monitor these issues closely and are collaborating with other cities to identify best practices in addressing these issues. It will take longer term solutions and strategies to resolve the long-term obligations including levering the economic growth that enhance the revenues and controlling our costs.

**Comment by evanwolf** [comment]
Not sure I'm recalling this correctly, but didn't we visualize the draft budgets as they were presented to the council for discussion? Four or five iterations and lots of scrambling to get the drafts.

**Comment by adstiles** [comment]
The mayor's proposed budget is the only draft budget that has a comprehensive data set; council proposals don't. The "open budget template", which I'm pursuing via the Budget Advisory Committee, would produce a data set (not as comprehensive as mayor's, more like a summary) for each council proposal. Still in progress.

**Comment by mikeubell** [comment]
Sounds like a good direction to be going.  Thanks.
