### ISSUE TITLE
Add link to City Budget Information

### ISSUE THREAD

**Issue by Mai-Ling** [openoakland/openbudgetoakland#56]
We'll use this page share resources including:

-data portal
-other videos that come out
-dates and engagement opportunities

Here's the link to the City Budget page:
http://www2.oaklandnet.com/Government/o/CityAdministration/d/BudgetOffice/ProposedBudget/index.htm

**Comment by evanwolf** [comment]
From where should we link to it?

**Comment by Mai-Ling** [comment]
Sorry- just noticed this! Okay- It would be great to include in that leading paragraph that's on the OpenBudget page.

**Comment by macfarlandian** [comment]
this looks to be out of date now, closing
