### ISSUE TITLE
Where is the feedback?

### ISSUE THREAD

**Issue by evanwolf** [openoakland/openbudgetoakland#57]
http://openbudgetoakland.org/feedback.html collects public suggestions. **Let's collect the comments to-date and share them with OO volunteers.** 
![obo-feedback](https://cloud.githubusercontent.com/assets/205622/7216819/5e717c4e-e5c1-11e4-8104-18228856c026.jpg)

**Comment by adstiles** [comment]
We now use Wufoo to collect feedback. I (and I think @ixley) receive feedback as emails. How would be best to share them?

I do prefer the old system where it was simply comments on the page for all to see. We had a long list of comments/feedback that is no longer visible.

**Comment by ixley** [comment]
I don't get the emails myself but I can make sure you have the Wufoo login
(so you can access all the feedback in one place) if you don't have it
already.

**Comment by hboylan** [comment]
If someone were to make some sort of game which allows people to budget government spending the way they saw fit, they could then apply Machine Learning to the data set in order to accurately predict a budget that would directly correlate to public opinion. 🙊

**Comment by macfarlandian** [comment]
i don't think it's clear from the form that people's feedback would be public so i'm not sure this is a good idea without a significant redesign and possibly replacing this form entirely. we already have comment forms for public discussion
