### ISSUE TITLE
1 infographic card per row

### ISSUE THREAD

**Issue by evanwolf** [openoakland/openbudgetoakland#58]
![slide1a](https://cloud.githubusercontent.com/assets/205622/7286721/f654fccc-e902-11e4-81c8-f110922443d2.jpg)
in a very basic way, i'd like each element of the tree to generate its own little pinable infographic "card" showing:
-  its place in the tree, 
- a name, 
- any attributes, and 
- a link back to its OBO page. 

for visuals, 
- dollar amounts compared to human-referencable things (7 Priuses, 3.5 FTE employees).

if there's history, show 
- up/down arrow if more than 10% change. 

so we'd have 9K+ infographics for people to share. and discuss

![slide2](https://cloud.githubusercontent.com/assets/205622/7286719/f650d19c-e902-11e4-9b26-dd67ea430475.png)

**Comment by ixley** [comment]
Cool idea. Definitely could make for more digestible pieces of the budget and support more dialogue.

**Comment by adstiles** [comment]
Awesome! Who can do it?

**Comment by cgosiak** [comment]
Hello @evanwolf I see that this is from a little while back, and this is my first attempt at working with a task I found on Code for America. Are you still in need of help on this project? And what is the correct way for me to begin work on this project if you are?

Definitely looking forward for an opportunity to help out!
