### ISSUE TITLE
URGENT: Front page redesigned as a landing page / portal for the budget process

### ISSUE THREAD

**Issue by adstiles** [openoakland/openbudgetoakland#60]
Kick off April 30 with mayor's proposed budget. Ask @adstiles for details.

**Comment by evanwolf** [comment]
Alameda County's budget portal home page
![screenshot-budget acgov org 2015-04-23 07-04-54](https://cloud.githubusercontent.com/assets/205622/7305354/0139d8c4-e9b2-11e4-9fca-df0ab3ec0aaa.png)

**Comment by evanwolf** [comment]
Marin County budget portal home page
![screenshot-marincountyca opengov com 2015-04-18 13-04-01](https://cloud.githubusercontent.com/assets/205622/7305371/2e5a4abe-e9b2-11e4-94be-d3f1621c119f.png)

**Comment by evanwolf** [comment]
Marin County budget portal home page 
![marincountyca opengov com_2015-04-18_13-03-16](https://cloud.githubusercontent.com/assets/205622/7305387/4f81a94e-e9b2-11e4-950c-26229b9195bf.png)

**Comment by evanwolf** [comment]
Cook County (Chicago) budget portal home
![lookatcook com_2015-04-18_13-02-26](https://cloud.githubusercontent.com/assets/205622/7305398/68266f3e-e9b2-11e4-9b56-0031f8d48480.png)

**Comment by adstiles** [comment]
This is in progress, check w/ @macfarlandian or @adstiles before starting
