### ISSUE TITLE
URGENT: budget comparison visualization(s) 

### ISSUE THREAD

**Issue by adstiles** [openoakland/openbudgetoakland#61]
Using never-before-public data, create a budget comparison tool that will have a big impact on Oakland's budget process (no hyperbole). Ideally with D3, the visualization(s) will make side-by-side comparison of the mayor's proposed budget and 2-3 council proposals. Ask @adstiles for details. 

Data will be collected in this format: https://docs.google.com/spreadsheet/ccc?key=0AqpW8uWGhwkudGlPTFJnb1hQU0xPdXgwdWwyR0VKUlE&usp=sharing#gid=9

Possible code / inspiration:

http://bl.ocks.org/mbostock/3943967

http://bl.ocks.org/mbostock/3886394

http://bl.ocks.org/mbostock/3886208

http://bl.ocks.org/mbostock/3887051

https://live.zoomdata.com/zoomdata/visualization?__target=embedded&key=544fb187e4b0f4966438c4c3#51db7ad4e4b04caf9ab346db-5411ace4e4b065842f0df371

**Comment by bayreporta** [comment]
Grouped Bar may be the best way to go for comparing the different budgets. Two charts, one for department expenses and one for source of revenue.

**Comment by mikeubell** [comment]
I like the normalized stacked bars.  Each bar would be a budget and the segments are the department allocations.  It would show what is gaining and what is loosing in comparison, budget to budget.

**Comment by mikeubell** [comment]
I think we should display what part of each category is funded by the General Fund and what part is funded by non-discretionary funds.  If we use bars, then for each category the bottom part of the bar would be the non-discretionary funds and the top part would be from the General Fund.  Perhaps with the non-discretionary part being the same color, but with cross hatching.

**Comment by mikeubell** [comment]
NOTE: The council will base their budgets on a revised forecast which will give them more money to spend than the mayor.

**Comment by jbaxley** [comment]
Hi, is there any update on this?

**Comment by macfarlandian** [comment]
released as of 13e529cf5fe530c5b008bdd8ab0f7076d8f00c32
