### ISSUE TITLE
Budget process timeline shouldn't show "12:00am" on all the items

### ISSUE THREAD

**Issue by npdoty** [openoakland/openbudgetoakland#62]
It's an easy fix, but it's to the data in the Google Spreadsheet, so I can't make a pull request. You need to change all the Start Date and End Date items so that they don't include hours/minutes/seconds. (When I clicked on each one, and then selected the date using the date picker, the sheet automatically updated to include the date but not the time.)

For example, see the first few items of my copy of the spreadsheet here:
https://docs.google.com/spreadsheets/d/1uPj_zOgjthPm3Ki4Bz4Mvr8APEq1Vpf-r9-qznMm_II/edit?usp=sharing
When I run the same code with this spreadsheet, it doesn't show the 12:00am times.

**Comment by adstiles** [comment]
Fixed, just had to change date format in google doc. Thanks!
