### ISSUE TITLE
Broken image links in budget process timeline

### ISSUE THREAD

**Issue by npdoty** [openoakland/openbudgetoakland#63]
Two images in the timeline are broken:
1. "Proposed Policy Budget Released": Image of the mayor (hotlink to an image of Jean Quan at zennie62, which does not load). Maybe use this image of Libby Schaaf from the Oakland city website: http://www2.oaklandnet.com/oakca1/groups/ceda/documents/image/oak051245.jpg
2. "Budget Town Hall Meetings and Community Input": Image of the map of city council districts (hotlink to a wiki cache image from oaklandwiki.org which no longer works). You could use this URL from the wiki which is an up-to-date cache image: https://oaklandwiki.org/media/cache/04/b7/04b77a395728f8e1f59ae98899fbca62.jpg Better, though, would be downloading the screenshot, hosting on some permanent site and then linking directly to it.

**Comment by npdoty** [comment]
Changes have to be made in this Google Spreadsheet (otherwise I would send you a pull request): https://docs.google.com/spreadsheets/d/1q98FI61uUSgiKWWf4QWfKMJdQdlPEz9jH3ZqGZePIvk/edit#gid=0
And the captions for those images may need to be updated as well.

**Comment by adstiles** [comment]
Fixed thanks!
