### ISSUE TITLE
In flow diagram change "Local Tax" to "Local (Parcel) Taxes"

### ISSUE THREAD

**Issue by adstiles** [openoakland/openbudgetoakland#67]

**Comment by howarddd** [comment]
Is there a text file i can fix?

**Comment by adstiles** [comment]
Done, just needs to be merged.

**Comment by howarddd** [comment]
But can I see the material??

Or is this a non-collaborative project?

**Comment by adstiles** [comment]
It's all right here, I'm not sure what you need me to do for you, but in any case I don't have time to help right now.

**Comment by howarddd** [comment]
I got to the doc a few min after this emali
