### ISSUE TITLE
Make temp. placeholder thumbnails for mayor's budget visuals

### ISSUE THREAD

**Issue by adstiles** [openoakland/openbudgetoakland#72]
Since we don't yet have the data for these visuals, but want to indicate that it's coming soon, create temporary/placeholder images. Reduce the opacity of the current image and overlay text: "Data for this visualization coming April 30" (open to suggestions on better/shorter text). 

This will allow us to launch the new site before the mayor's announcement on 4/30.

![screen shot 2015-04-28 at 2 47 57 pm](https://cloud.githubusercontent.com/assets/2553203/7381151/9b579926-edb5-11e4-9a49-0403a8af811a.png)

**Comment by adstiles** [comment]
Will replace the images here -- THIS SITE IS NOT LIVE -- don't circulate other than for dev purposes: http://staging.openbudgetoakland.org/

**Comment by elinaru** [comment]
Disabled detailed breakdown graphic with "coming soon…" text: 
![budget-squares-soon](https://cloud.githubusercontent.com/assets/6467815/7384184/75b201a2-ede2-11e4-8adf-c954a976ddf1.png)

**Comment by elinaru** [comment]
![revenue-expenses-soon](https://cloud.githubusercontent.com/assets/6467815/7384438/f217e2fc-ede7-11e4-8650-c30ad666411d.png)
