### ISSUE TITLE
Add budget forum map to front page

### ISSUE THREAD

**Issue by adstiles** [openoakland/openbudgetoakland#78]
Laura Daly gave permission to use her budget forum map. 

Add to front page between Budget Calendar Key Dates and the Twitter feed.

Here is the embed code:

```<iframe width='100%' height='520' frameborder='0' src='https://lauraginfo.cartodb.com/viz/913f4dcc-eeb3-11e4-9084-0e49835281d6/embed_map' allowfullscreen webkitallowfullscreen mozallowfullscreen oallowfullscreen msallowfullscreen></iframe>```

and the link:
http://cdb.io/1JTIpib

**Comment by adstiles** [comment]
iframe code not visible in comment above ...


<iframe width='100%' height='520' frameborder='0' src='https://lauraginfo.cartodb.com/viz/913f4dcc-eeb3-11e4-9084-0e49835281d6/embed_map' allowfullscreen webkitallowfullscreen mozallowfullscreen oallowfullscreen msallowfullscreen></iframe>

**Comment by mikeubell** [comment]
The map does not fit properly in a 1/3 extent.  The search bar gets placed over the title.  I don't know how to change that.  I can put it above or below the Dates and Twitter feed.

**Comment by adstiles** [comment]
Can you put it BELOW the dates. So still split in 1/2, left side is budget dates (above) AND map (below) and right side is twitter feed? Thanks!

**Comment by mikeubell** [comment]
Still does not work.  It wants to be full width.  Maybe Laura can change the map?

**Comment by mikeubell** [comment]
Laura provided a new map without the search bar.  Looks good.  I have split the row 4/5/3 to give the map a little more room.

**Comment by adstiles** [comment]
thanks - I thought the change should show up here on the staging site but not seeing it yet. http://staging.openbudgetoakland.org/

**Comment by evanwolf** [comment]
The embed is making the whole page load slower (or at least it feels that way). We're loading the entire map and cartodb app for every user. 

Can we replace the embed with a _picture_  of the embed? One file call instead of cartodb's 30? Smaller payload too.
![eventfinder](https://cloud.githubusercontent.com/assets/205622/7433689/b6f379b8-efe8-11e4-9983-960eee36d10a.jpg)

**Comment by adstiles** [comment]
I hear that (though it loads fast enough for me) but it needs to be a live map in order to show the location addresses.

**Comment by adstiles** [comment]
I hear that (though it loads fast enough for me) but it needs to be a live
map in order to show the location addresses.

On Fri, May 1, 2015 at 10:02 AM, Phil Wolff <notifications@github.com>
wrote:

> The embed is making the whole page load slower (or at least it feels that
> way). We're loading the entire map and cartodb app for every user.
>
> Can we replace the embed with a *picture* of the embed? One file call
> instead of cartodb's 30? Smaller payload too.
> [image: eventfinder]
> <https://cloud.githubusercontent.com/assets/205622/7433689/b6f379b8-efe8-11e4-9983-960eee36d10a.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openoakland/openbudgetoakland/issues/78#issuecomment-98178201>
> .
>



-- 
Adam Stiles
510.280.4862
