### ISSUE TITLE
design bug: Start the tree with multiple departments showing

### ISSUE THREAD

**Issue by evanwolf** [openoakland/openbudgetoakland#84]
the link from the home page starts here... 
http://openbudgetoakland.org/2015-17-proposed-budget-tree.html#fy15-16.expense
![screen shot 2015-05-01 at 5 11 14 pm](https://cloud.githubusercontent.com/assets/205622/7439096/2999c62a-f025-11e4-8249-667f2bbad8b5.png)

It should start here... 
http://openbudgetoakland.org/2015-17-proposed-budget-tree.html#fy15-16.expense.fy15-16
![screen shot 2015-05-01 at 5 13 40 pm](https://cloud.githubusercontent.com/assets/205622/7439103/774b0564-f025-11e4-883a-8890e0c5bdf7.png)

**Comment by adstiles** [comment]
Agreed, and we had the same feedback from 2 other people via twitter. @ppopp can you handle?

**Comment by macfarlandian** [comment]
looks like this was fixed at some point but the issue wasn't closed
