### ISSUE TITLE
Treemap not rendering properly on Internet Explorer

### ISSUE THREAD

**Issue by adstiles** [openoakland/openbudgetoakland#87]
Explorer is used by many (most?) city staff, so this is important. Let us know if anyone can help.

A staff member says the rectangles are rendering but not the numbers.

**Comment by evanwolf** [comment]
I'm having the same bug on Firefox.

**Comment by ppopp** [comment]
I pushed a fix into the dev-treemap branch and tested it on firefox (sorry, no access to IE at the moment).  Looks like it's part of the pull request #86 for the development branch.  I'll leave it to y'all to integrate.
